from . import audit_mixin
from . import pharmacy_master
from . import pharmacy_patient
from . import pharmacy_prescriber
from . import pharmacy_staff
from . import pharmacy_medicine
from . import pharmacy_prescription
from . import pharmacy_dispensing
from . import pharmacy_alert
from . import pharmacy_register
from . import res_partner
from . import sale_order
from . import sale_pharmacy_prescription
from . import sale_pharmacy_dispensing
from . import pos_pharmacy_prescription
from . import pos_order
from . import pos_product_template
from . import report_pharmacy_patient
