from odoo import api, fields, models, _
from odoo.exceptions import UserError


class PharmacyRegisterEntry(models.Model):
    _name = "pharmacy.register.entry"
    _description = "Pharmacy Regulatory Register Entry"
    _order = "entry_datetime desc, id desc"
    _rec_name = "prescription_id"

    register_type_id = fields.Many2one(
        "pharmacy.register.type",
        required=True,
        ondelete="restrict",
        index=True,
        readonly=True,
    )
    entry_datetime = fields.Datetime(required=True, index=True, readonly=True)
    movement_type = fields.Selection(
        [
            ("receipt", "Received"),
            ("dispense", "Dispensed"),
            ("adjustment", "Adjusted"),
            ("reversal", "Reversal"),
        ],
        required=True,
        index=True,
        readonly=True,
    )
    patient_id = fields.Many2one("pharmacy.patient", index=True, readonly=True)
    prescriber_id = fields.Many2one("pharmacy.prescriber", index=True, readonly=True)
    prescription_id = fields.Many2one("pharmacy.prescription", index=True, readonly=True)
    dispensing_id = fields.Many2one("pharmacy.dispensing", index=True, readonly=True)
    dispensing_line_id = fields.Many2one("pharmacy.dispensing.line", index=True, readonly=True)
    product_id = fields.Many2one("product.product", required=True, index=True, readonly=True)
    lot_id = fields.Many2one("stock.lot", index=True, readonly=True)
    expiry_record_id = fields.Many2one(
        related="dispensing_line_id.expiry_record_id",
        string="Pharmacy Expiry",
        store=True,
        readonly=True,
    )
    expiry_date = fields.Date(
        related="dispensing_line_id.expiry_date",
        store=True,
        readonly=True,
    )
    quantity_in = fields.Float(digits="Product Unit of Measure", readonly=True)
    quantity_out = fields.Float(digits="Product Unit of Measure", readonly=True)
    product_uom_id = fields.Many2one("uom.uom", required=True, readonly=True)
    pharmacist_id = fields.Many2one("pharmacy.staff.profile", readonly=True)
    source_reference = fields.Char(index=True, readonly=True)
    company_id = fields.Many2one("res.company", required=True, index=True, readonly=True)
    notes = fields.Char(readonly=True)

    @api.model_create_multi
    def create(self, vals_list):
        if not self.env.context.get("allow_pharmacy_register_create"):
            raise UserError(_("Register entries can only be generated by validated pharmacy transactions."))
        return super().create(vals_list)

    def write(self, values):
        raise UserError(_("Regulatory register entries are immutable."))

    def unlink(self):
        raise UserError(_("Regulatory register entries cannot be deleted."))
