{
    "name": "Noel's Pharmacy Dispensing",
    "summary": "Complete patient, prescription, dispensing, POS, sales, website and regulatory reporting",
    "version": "19.0.2.0.1",
    "category": "Sales/Point of Sale",
    "author": "Noel's Pharmacy & Wellness Center Ltd",
    "website": "https://noelspharmacy.com",
    "license": "LGPL-3",
    "depends": [
        "base",
        "contacts",
        "mail",
        "product",
        "stock",
        "sale_management",
        "sale_stock",
        "point_of_sale",
        "website_sale",
        "portal",
    ],
    "data": [
        "security/pharmacy_security.xml",
        "security/ir.model.access.csv",
        "data/pharmacy_sequence.xml",
        "data/pharmacy_register_type.xml",
        "views/pharmacy_patient_views.xml",
        "views/pharmacy_prescriber_views.xml",
        "views/pharmacy_staff_views.xml",
        "views/pharmacy_medicine_views.xml",
        "views/pharmacy_prescription_views.xml",
        "views/pharmacy_dispensing_views.xml",
        "views/pharmacy_register_views.xml",
        "views/pharmacy_alert_views.xml",
        "views/pharmacy_audit_views.xml",
        "views/res_partner_views.xml",
        "report/pharmacy_label_report.xml",
        "views/sale_order_views.xml",
        "views/pos_order_views.xml",
        "views/pharmacy_website_templates.xml",
        "views/pharmacy_menu.xml",
        "views/pharmacy_report_wizard_views.xml",
        "views/pharmacy_patient_report_views.xml",
        "report/pharmacy_inspection_report.xml",
        "report/pharmacy_patient_history_report.xml",
    ],
    "assets": {
        "point_of_sale._assets_pos": [
            "noels_pharmacy/static/src/app/pharmacy_prescription_dialog.js",
            "noels_pharmacy/static/src/app/pharmacy_prescription_dialog.xml",
            "noels_pharmacy/static/src/app/pharmacy_pos_patch.js",
            "noels_pharmacy/static/src/app/pharmacy_control_buttons.xml",
            "noels_pharmacy/static/src/app/pharmacy_pos.scss",
        ],
    },
    "application": True,
    "installable": True,
    "auto_install": False,
}
